name: Deploy React App to Hostinger (shop subdomain)

on:
  push:
    branches:
      - main

jobs:
  deploy-shop:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build React application
        run: npm run build
        env:
          CI: false  # Avoids some strict warnings in CI

      # Verify what's inside dist/ (helps debugging)
      - name: Check dist/ contents
        run: |
          ls -la dist/
          ls -la dist/assets/

      - name: Prepare deployment directory
        run: |
          mkdir -p public_html/shop
          cp -r dist/index.html dist/assets public_html/shop/
          ls -la public_html/shop/  # Confirm files copied

      - name: Deploy to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: anoy369.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: public_html/shop/
          remote_dir: /public_html/shop/
          exclude: |
            **/node_modules/**
            **/.git/**
            *.git*
            **/README.md
            **/package.json
            **/package-lock.json
            **/npm-debug.log
            **/.*            
